- name: Stop unnecessary services
  service: name={{ item }} state=stopped enabled=no
  with_items: centos_common_unnecessarry_services
  ignore_errors: yes

- name: Update yum packages
  yum: name=* state=latest

- yum: name="@Japanese Support" state=present
- yum: name="@Base" state=present

- name: Intall yum packages
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - clamd
    - compat-libtermcap
    - ctags
    - curl
    - gcc
    - gdbm-devel
    - git-core
    - ipa-pgothic-fonts
    - jq
    - libyaml-devel
    - lv
    - make
    - man
    - mercurial
    - ncurses-devel
    - nkf
    - openssl-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - python-psycopg2
    - readline-devel
    - rpm-build
    - subversion
    - unzip
    - wget
    - zip
    - zlib-devel

# - shell: freshclam
#   sudo_user: clam
# 
# - name: Start unnecessary services
#   service: name={{ item }} state=started enabled=yes
#   with_items:
#     - clamd

