- name: Stop unnecessary services
  service: name={{ item }} state=stopped enabled=no
  with_items: centos_common_unnecessarry_services
  ignore_errors: yes

- name: Update yum packages
  yum: name=* state=latest

- yum: name="@Japanese Support" state=present
- yum: name="@Base" state=present

- name: Intall yum packages
  yum: name={{ item }} state=present
  with_items:
    - autoconf
    - clamd
    - compat-libtermcap
    - ctags
    - curl
    - gcc
    - gdbm-devel
    - git
    - ipa-pgothic-fonts
    - jq
    - libyaml-devel
    - make
    - man
    - mercurial
    - ncurses-devel
    - nkf
    - openssl-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - python-psycopg2
    - readline-devel
    - rpm-build
    - subversion
    - unzip
    - wget
    - zip
    - zlib-devel
    - http://archives.fedoraproject.org/pub/archive/fedora/linux/core/6/x86_64/os/Fedora/RPMS/lv-4.51-8.1.x86_64.rpm 

- get_url: url=http://ftp.jaist.ac.jp/pub/OpenBSD/OpenSSH/portable/openssh-{{ openssh_version }}.tar.gz dest=/usr/local/src/openssh-{{ openssh_version }}.tar.gz
  tags: [ openssh ]
- name: Install openssh.
  shell: sudo tar xf openssh-{{ openssh_version }}.tar.gz; cd openssh-{{ openssh_version }}; sudo ./configure; sudo make; sudo make install
  args:
    chdir: /usr/local/src
    creates: /usr/local/bin/ssh
  tags: [ openssh ]

# - shell: freshclam
#   sudo_user: clam
# 
# - name: Start unnecessary services
#   service: name={{ item }} state=started enabled=yes
#   with_items:
#     - clamd

