- name: Stop unnecessary services
  service: name={{ item }} state=stopped enabled=no
  with_items: centos_common_unnecessarry_services
  ignore_errors: yes

- yum: name="@Japanese Support" state=present
- yum: name="@Base" state=present

- name: Intall yum packages
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
    state: latest
  with_items:
    - autoconf
    - ctags
    - curl
    - gcc
    - gdbm-devel
    - git
    - ipa-pgothic-fonts
    - jq
    - libyaml-devel
    - make
    - man
    - mercurial
    - ncurses-devel
    - nkf
    - openssl-devel
    - perl-ExtUtils-Embed
    - perl-devel
    - python-devel
    - python-psycopg2
    - readline-devel
    - unzip
    - wget
    - zip
    - zlib-devel

- get_url: url=http://ftp.jaist.ac.jp/pub/OpenBSD/OpenSSH/portable/openssh-{{ openssh_version }}.tar.gz dest=/usr/local/src/openssh-{{ openssh_version }}.tar.gz
  tags: [ openssh ]
- name: Install openssh.
  shell: sudo tar xf openssh-{{ openssh_version }}.tar.gz; cd openssh-{{ openssh_version }}; sudo ./configure; sudo make; sudo make install
  args:
    chdir: /usr/local/src
    creates: /usr/local/bin/ssh
  tags: [ openssh ]

